meganz/mingw-std-threads

mingw.condition_variable.h

If you try to compile code with -Wall -Werror the code won't compile.

Reorder variable declarations to omit -Wreorder

---

mingw.thread.h

Both `this_thread::get_id()` and `this_thread::yield()` need to be marked as
inline, to avoid linker errors about multiple definitions.

Mark global functions as inline.

---

mingw.condition_variable.h
mingw.mutex.h
mingw.thread.h

I fixed a few interface/compatibility bugs here and there; the most prominent one is the incorrect "non-`const` copy constructor" of your `std::thread` implementation, which should be a move constructor (this triggered some errors in my codebase).
Also, in headers other than `mingw.thread.h` there are some missing includes, which probably went unnoticed because other versions of the mingw toolchain already include them in some other common header.

Various interface/include fixes

---

mingw.condition_variable.h
mingw.mutex.h
mingw.thread.h
tests/CMakeLists.txt

hello,
First commit "qualify exceptions and chrono with std": 
I found mingw.thread.h also useful when building in static with MSVC, because MSVC's std::thread pull >100 kB of Concurrency Runtime even when only used to create a new thread... (ironically the Concurrency Runtime is not used anymore in MSVC2015 to *create* threads, however in its std::thread class implementation a condition variable is used - for no real reason it seems - and both mutex and condition variable still use the Concurrency Runtime...)
My approach is to just take the mingw.thread.h file and change the namespace, and do a e.g. "using win32_std::thread" in the application code. Therefore, this patch qualify uses of system_error, generic_category, and chrono with std:: so that they resist the potential englobing …

add std qualifications & check result of _beginthreadex & cleanups

---

mingw.condition_variable.h

The `condition_variable::wait_until` should call base class's `wait_until` rather than `wait_for`.

Fix typo bug for condition_variable::wait_until

---

mingw.condition_variable.h

Both `condition_variable_any::notify_one` and `condition_variable_any::notify_all`
are marked `noexcept`, so they are not allowed to throw. Since a `throw()` will
automatically call `std::terminate()`, it seems reasonable to call it directly.
This change fixes GCC warnings from -Wterminate while retaining the same
runtime behaviour.

Remove throws in noexcept methods.

---

mingw.condition_variable.h

This PR fixes a race condition between condition_variable::notify_one and wait_impl.
To trigger the race condition the following events need to occur:
1. Suppose we have a condition_variable cv and at least 2 threads.
2. Thread A enters wait_impl and stops at WaitForSingleObject with a finite timeout, mNumWaiters==1 at this point
3. Thread B enters notify_one, checks !mNumWaiters and the scheduler stops it before executing mNumWaiters.load()
4. WaitForSingleObject times out at Thread A and wait_impl returns. mNumWaiters==0
5. Thread B continues and sets targetWaiters to -1, causing an infinite loop while waiting for mNumWaiters to become -1
The fix is simple, only read mNumWaiters once during setup, so timeouts won't cause problems.

Fix possible race condition in condition_variable

---

mingw.thread.h

I added ostream& operator<<( ostream& s, const thread::id& id) operation, so i  can use std::count << std::this_thread::get_id() << std::endl;  to output the thread id , like real c++11 thread.

add std::cout << std::this_thread::get_id() << std::endl;  operation

---

mingw.thread.h

Use direct initialization from a function to the static variable to
leverage the implicit locking provided by the compiler. This avoids the
(very theoretical) race condition of concurrent initialization;
shouldn't matter on x86 (where all `DWORD` stores are atomic), may matter
on other architectures.

std::thread::hardware_concurrency: avoid race conditions in initialization

---

mingw.thread.h

Fixed various nonconforming bits:
- added several missing `noexcept` specifiers;
- fixed `std::thread::id::operator==` (the standard mandates it to be a free function);
- added missing operators on `std::thread::id` (allow it to be used as a key in a `std::map`).

Various thread id standard conforming fixes

---

mingw.thread.h
tests/tests.cpp

- Adds specialization of the `hash` class template for `thread::id`
objects., to comply with the standard.
- Adds tests for serialization and hashing to `tests.cpp`.

Add hash for thread::id

---

mingw.shared_mutex.h
tests/tests.cpp

- Adds all classes that are intended to be supplied by <shared_mutex>.
- Adds tests for `shared_mutex`, `shared_lock`, `condition_variable_any`.
Notable features:
- Selects implementation (native or portable) based on target Windows version.
- Various namespace tricks provide conditional inclusion. Implementation files are brought into `std` if and only if `std` doesn't supply them. Unlike preprocessor-based solutions, this should be compatible with the practice of including a header inside a namespace. For example,
`namespace tmp {
#include "mingw.shared_mutex.h"
}`
will cause the implementation to place objects in namespace `tmp::std`, regardless of the presence of an official implementation in `std`, while
`#include "mingw.shared_mutex.h"`
will cause the implementation to place objects …

Header shared_mutex

---

mingw.mutex.h

- Reduces strictness of memory order in `call_once`. The Release-Acquire ordering is strong enough to satisfy the standard and will avoid locking all cores during passive calls, unlike the default Sequentially-Consistent ordering.
- Because the original `call_once` implementation requires `<mutex>`, the header's implementations of `lock_guard`, etc. are never included. This pull request removes them.

Improve call_once

---

mingw.condition_variable.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h
tests/tests.cpp

- Moves the implementation to its own namespace, `mingw_stdthread`, and removes the `#error` that occurs when including the implementation alongside GCC's implementation. This makes simultaneous inclusion of both implementations safe.
- Removes the namespace inclusion trick from `mingw.shared_mutex.h`. No ambiguity occurred when objects specified a namespace with `std::`, but `using namespace std;` fully flattens the namespace tree, which could have introduced ambiguity.
- Added a check for the presence of MinGW before including files into `std`. This should allow the library to be used as-is with Visual Studio, etc., but might cause `custom_namespace::std` to be empty if the header is included inside `custom_namespace`. To achieve compatibility with legacy code with minimal changes, one …

Make use alongside standard implementations safe

---

README.md
mingw.condition_variable.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h
tests/tests.cpp

- Add native implementation of condition_variable if targeted Windows version is detected to be Vista or higher. This can noticeably improve performance.
- Update the README with information about how to target different Windows versions.

Native condition_variable if targeting Windows Vista

---

mingw.condition_variable.h
mingw.mutex.h
mingw.thread.h

Resolves standard-compliance issues for `thread` and `call_once`. Specifically, these are to behave as if they use `std::invoke`, a C++17 feature. This pull request
- Implements `invoke` for C++11 and C++14.
- Uses `invoke` for calls in `thread` and `call_once`.

Implement and use invoke for thread and call_once

---

mingw.condition_variable.h
mingw.thread.h

As mentioned in #39 , the library is currently incompatible with Windows Phone 8. Two changes are necessary. Specifically:
- GetSystemInfo in mingw.thread.h must be replaced with GetNativeSystemInfo. This can affect behavior of 32-bit software emulated on 64-bit Windows by WOW64, but this should be harmless (generating too few or too many threads for the emulator may reduce performance, but this should still give a good match for the hardware).
- Semaphores needed to be removed. Specifically, the XP-compatible `condition_variable` classes needed to be removed or replaced. I have opted to remove them except when compiling for XP. Because there is already a native `condition_variable` implementation for Vista and higher, this change should be undetectable to users unless they are explicitly …

Tentative support for Windows Phone 8

---

mingw.condition_variable.h
mingw.mutex.h

When compiling for Windows XP, many workarounds are required to ensure standard-compliance. In particular, the `xp::mutex` class both uses a CriticalSection object and deferred initialization.
For Windows Vista, the more lightweight SRW Locks can be used internally for both `once_flag` and `condition_variable_any`. This pull request switches the internal mutexes used when compiling for Windows Vista to be as modern as is available.
This pull request also fixes a potentially unterminated loop that could occur if an instance of `xp::mutex` is locked in one thread while another thread is in the process of initializing it.

Improve performance for Vista, fix bug with deferred initialization

---

mingw.condition_variable.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h
tests/tests.cpp

Improves debugging features of the library. Specifically,
- Adds recursion checking for all exclusive-mode operations in `shared_mutex`.
- Adds an explanatory message (instead of just calling `std::terminate()`) if `NDEBUG` is undefined and a thread is moved to or destroyed while in a joinable state.
- Makes certain cases of inheritance private to better conform to the standard.

Enhanced debugging

---

mingw.future.h
mingw.mutex.h
mingw.thread.h
tests/tests.cpp

Implements core features of the C++11 `<future>` header. Specifically, this pull request adds support for 
- `future`
- `shared_future`
- `promise`
- `async`
Some work yet remains before the library can be considered final. Specifically,
- `packaged_task` is not yet implemented.
+ It can be implemented as a wrapper around `std::function` and a `promise`, or the classes internal to `mingw.future.h` can be employed.
- The implementation of `promise<T>::set_value_at_thread_exit` currently uses a second "helper thread" that detects when the original thread exits. This is, of course, inefficient, but I do not yet know another way to ensure that the value is set only after all `thread_local` objects are destroyed. This approach should be replaced later, if doing so is possible.
Though …

Core features from <future>

---

mingw.thread.h

Win32 Sleep() takes an unsigned int for milliseconds, so this function would break if you passed it a negative value (calling sleep_until with a time in the past) or a duration longer than 49.7 days.

Fix sleep_for with large/negative values.

---

mingw.condition_variable.h
mingw.future.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h

- In `condition_variable`, fix potential for large wait times to act as if an indefinite wait were requested.
- In `mutex`, fix similar problems in `try_lock_for`.
- Fix a bug related to `make_shared` for template specialization `future<void>`.
- Resolve cast warnings in `thread` by altering later code (is now more robust) rather than simply silencing them.

Various bug fixes

---

mingw.condition_variable.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h

- Give a descriptive error when the user is targeting a version of Windows that lacks features vital to the library. Specifically, if a version of Windows earlier than Windows XP is being targeted either intentionally or by default. Addresses #49.
- Change method of finding values not equal to `CONDITION_VARIABLE_LOCKMODE_SHARED`. The value to be used when this constant is _not_ desired is undocumented in Microsoft's website, as is the value of the constant itself. The change made here changes to generating a different value, instead of assuming (and asserting) a specific value.

Descriptive error on insufficient Windows version.

---

mingw.condition_variable.h
mingw.future.h
mingw.invoke.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h

To reduce macro pollution, as in #54, replaces `windows.h` with some of its component headers. Likewise, break a dependency on `mingw.thread.h` by separating the `invoke` implementation (used by 3 headers) into its own file.

Minimize Windows headers

---

README.md
mingw.condition_variable.h
mingw.future.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h
mingw.throw.h
tests/tests.cpp

To be able to build without exceptions enabled. Required for Clang + Mingw with "-fno-exceptions" flag.

Add -fno-exceptions support

---

mingw.thread.h
tests/tests.cpp

In #58 , @phma noticed an issue, in that threads which were passed an argument in a for loop were not properly disambiguated by it. I have replicated the behavior, and determined that it is caused by the thread constructor not properly copying its arguments. This is a fatal flaw, so it must be addressed immediately.
This pull request eliminates the problem using the following steps:
- Force use of the standard's prescribed behavior (make a copy of type `std::decay<T>::type` for each argument of the thread's constructor).
- Add regression test to identify (and treat as fatal) this flaw if it is reintroduced.
I recommend immediately updating this library. All projects that use this library should update their copy and recompile.
@alxvasilev , please merge this *ASAP*.

Fix fatal bug: Threads must copy arguments.

---

mingw.invoke.h
mingw.thread.h
tests/tests.cpp

Standard-compliance improvements:
- Removes public non-default constructor from `thread::id`.
- Adds regression test for `thread::id`'s TriviallyCopyable property.
Robustness improvements:
- Replace an instance of undefined behavior (`DWORD *` reinterpreted as `unsigned *`) with standard-compliant behavior (pass pointer to existing unsigned, statically cast the result to DWORD).
(Possible) performance improvements:
- Remove possibility of compiler failing to inline a wrapper function by calling directly.

Miscellaneous improvements

---

mingw.condition_variable.h
mingw.future.h
mingw.mutex.h
mingw.shared_mutex.h
mingw.thread.h

MinGW-w32's version of the Windows API is lacking certain headers. In particular, it includes `windows.h`, but not the more granular headers such as `synchapi.h`. Though the library's users would be best served by upgrading to MinGW-w64, supporting the legacy MinGW-w32 should increase the versatility of the library with minimal effort.

Detect when MinGW-w32 is used

---

cmake_stdheaders_generator/CMakeLists.txt

try_compile() of a single source file will use the right compiler and
compiler flags which were not handled by the execute_process() call
before. In particular, this allows to use clang++ as the compiler and
pass CMAKE_CXX_COMPILER_TARGET=x86_64-w64-mingw32 to cmake instead of
relying on the compiler being x86_64-w64-mingw32-g++.

Use try_compile() when retrieving the header paths.

---

mingw.mutex.h

Fixes the `timed_mutex` class to have a constructor (was failing due to the base class being inherited privately). This fixes #84 .
Adjusts the second read in `call_once` to use relaxed semantics, rather than acquire semantics. This should slightly improve performance, and is correct because this second load occurs after acquiring the mutex, which in itself acquires the result of the called function.

Fix timed mutex, tweak call_once

---

cmake_stdheaders_generator/CMakeLists.txt
mingw.latch.h
tests/tests.cpp
utility_scripts/Generate-StdLikeHeaders.ps1

Hello, this is my first contribution to this repository. I saw there are open issues for some C++20 features and since `latch` looked pretty easy I gave it a go. As suggested by the person that created the issue I used `<atomic>` based implementation. This means it may render this feature unusable on Windows versions older than Vista. However, it greatly simplifies the code and it seems it is the choice of other C++ STL implementations.
I tried my best to follow the conventions of this repository but I invite any reviewer to check if I am missing any special header guard, especially at the bottom of the file to check in an implementation is already available.
Closes #67

Add latch header implementation
